### ISSUE TITLE
Specify software dependencies

### ISSUE THREAD

**Issue by ghost** [idleberg/node-makensis#1]
README would be more helpful if it had any details on the following:

* What versions of makensis works with this project
* Operating Systems this lib supports
* Does this require WINE? Under what scenarios?

**Comment by idleberg** [comment]
Some good points, and I will update the README with some of your suggested information. Until then, here is some upfront info:

> What versions of makensis works with this project

Due to the excellent backward-compatibility, you can expect this library to run with version 3.x and most 2.x versions. Support for 2.x might be limited, since some features are exclusive to newer versions of `makensis`. Unfortunately, this is poorly documented in the [NSIS changelog](http://nsis.sourceforge.net/Docs/AppendixF.html#history). As a rule of thumb: this library was designed with NSIS v3.01 in mind. Features unavailable in older builds will either throw errors or simply be ignored.

I _know_ that the `-PPO` / `-SAFEPPO` parameters, as well as strict compilation (`-WX`), are only supported by NSIS 3.x. I _assume_ that the same is true for the for `-INPUTCHAR`/ `-OUTPUTCHAR`, but I can't verify that assumption.

> Operating Systems this lib supports

The `makensis` compiler is available for POSIX platforms and I've _seen_ it being available for Windows, macOS, Linux and some BSDs. I'm not sure if Node itself is available on each platform supported by `makensis`, I only use Windows, macOS and Linux in my day to day work.

> Does this require WINE?

No. I'd always recommend using the native compiler, but if you can't, Wine is a supported option.

**Comment by idleberg** [comment]
I've added prequisites and an additional disclaimer in the latest commits

**Comment by ghost** [comment]
Thanks! And thanks for the open sourcing the tool and making it available.
